version: '3.8'
services:
  inference:
    container_name: inference
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.inference
    command: python -u /app/app.py
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://inference:8000/inference/${TOKEN}"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - ./inference-data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  updater:
    container_name: updater
    build:
      context: .
      dockerfile: Dockerfile.updater
    environment:
      - INFERENCE_API_ADDRESS=http://inference:8000
    command: >
      sh -c "
      while true; do
        python -u /app/update_app.py;
        sleep 24h;
      done
      "
    depends_on:
      inference:
        condition: service_healthy
    volumes:
      - ./inference-data:/app/data

  worker:
    container_name: worker
    image: alloranetwork/allora-offchain-node:v0.9.1
    volumes:
      - ./worker-data:/data
    depends_on:
      inference:
        condition: service_healthy
    env_file:
      - ./worker-data/env_file

volumes:
  inference-data:
  worker-data:
